const TAB_NAVI_NAME = ['行情','模拟交易','资讯','我的'];

const TAB_NAVI_HEADER_BGCOLOR = '#222D3D';
const TAB_NAVI_BOTTOM_BGCOLOR = '#1C2533';
const TAB_NAVI_ACTIVE_TINT_COLOR = '#A1CBFF';
const HEADER_TINT_COLOR = '#5F6E82';
export {
  TAB_NAVI_NAME,

  TAB_NAVI_HEADER_BGCOLOR,
  TAB_NAVI_BOTTOM_BGCOLOR,
  TAB_NAVI_ACTIVE_TINT_COLOR,
  HEADER_TINT_COLOR
}